name: Docker
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docker_publish:
    name: Docker build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: taleshape/shaper:latest

